from Bio.Seq import Seq
from helpers import filter_seqs
import pytest


def test_null_seq():
    with pytest.raises(AssertionError):
        filter_seqs.process_seq_by_class(None, None)


def test_seq_not_changed():
    seq_without_x = Seq(
        (
            "TTTTTATAAGAATTGCAGTGTGATACGAAATACTAGAACATCATTTTATAATCCGTGTAATAAAAATTATAAT"
            "CTAGTATGTGTACTGCATTAGATCAATGGTTTTATATATATATCTATATAGTTTATCGTGCTTATTTAACGAA"
            "CGCTTTGTAAAAAAGTGTTTTTTTTTTTTGTATAAGCATTCACATTATTAAAAACATTATTATCAATTAATTT"
            "GAAAATTTTATTTCTATATTATATTATCGCAGGTATCGAGTATAATTACGCGAACACGATGCGGCATCTTTTT"
            "CAATATTATAAAATAATTATATATGTATAATAATTACCTATAATAGATTCAATAATAAATATTCATTTAAAAT"
            "ATCTCTTAAAAGAGTTTTTTCTTTACAGCGGTATATCTTTCCATATAGTTATCATAACCATCAAGATTAGCAA"
            "ATTGTTTTATCTCAAATAAATTTCCTTCAACAGACAGGACTGAAATTTTAGAATTTTTCAAAATTTTACTAGG"
            "TATTGCATTCAGTTGTAAACAATTTTCTTCAAGTCTTAATGT"
        )
    )

    assert filter_seqs.process_seq_by_class(seq_without_x, None) == seq_without_x


def test_class1_trimming():
    class_1 = Seq(
        (
            "ACTCTTTNCTCAGCTATGCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXACTGGAATCGGA"
            "ATGCGCCGCACCAGGAGAAAAACCACGGTTCCTTGGTGTTCGCGAGCAGCGAGTAACGCATATTTTAATCTTT"
            "TTGATGATCGGTTGTTCGGTCCTACTCACACCAATGTTGAGACACATACCTATGCCGGTATTATTCGGCGTTT"
            "TTCTTTATATGGGAGTCGCTTCGTTGAAAGGACTTCAATTTTTCGACAGAATTTTAATTATGTTGATGCCGGT"
            "TAAATACCAACCCGATTATATGTTTCTTCGTCAGGTACCTCGGCCGCGACCACGCTXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA"
        )
    )
    expected = Seq(
        (
            "ACTGGAATCGGAATGCGCCGCACCAGGAGAAAAACCACGGTTCCTTGGTGTTCGCGAGCAGCGAGTAACGCAT"
            "ATTTTAATCTTTTTGATGATCGGTTGTTCGGTCCTACTCACACCAATGTTGAGACACATACCTATGCCGGTAT"
            "TATTCGGCGTTTTTCTTTATATGGGAGTCGCTTCGTTGAAAGGACTTCAATTTTTCGACAGAATTTTAATTAT"
            "GTTGATGCCGGTTAAATACCAACCCGATTATATGTTTCTTCGTCAGGTACCTCGGCCGCGACCACGCT"
        )
    )

    assert filter_seqs.process_seq_by_class(class_1, 1) == expected


def test_class3_trimming():
    class_3 = Seq(
        (
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXACCTCCTATATATATATGTA"
            "TATATATATATATATATCAATGTGTAATACCGCTAGTTTTCTCTCGATTCGTTCGAAAATTGTGGCTCTTTCG"
            "GGCGAAACCGGCTGGGTCTGTGTGTACTCTCATCCTGTTTCGTGAACCGAAAGCTCCCTTTCTCCGAAGAAGA"
            "AGAATACATTTTTTTTTCGTGCGCGTAACACGCAACGGGCATTAAGTTACAAACGAAACGAGCTTTACCGCGT"
            "TCCTTCCCTTTAAGGGAGTCGCGGATGTTATACAAATGAAAAGAAAAAG"
        )
    )
    expected = Seq(
        (
            "ACCTCCTATATATATATGTATATATATATATATATATCAATGTGTAATACCGCTAGTTTTCTCTCGATTCGTT"
            "CGAAAATTGTGGCTCTTTCGGGCGAAACCGGCTGGGTCTGTGTGTACTCTCATCCTGTTTCGTGAACCGAAAG"
            "CTCCCTTTCTCCGAAGAAGAAGAATACATTTTTTTTTCGTGCGCGTAACACGCAACGGGCATTAAGTTACAAA"
            "CGAAACGAGCTTTACCGCGTTCCTTCCCTTTAAGGGAGTCGCGGATGTTATACAAATGAAAAGAAAAAG"
        )
    )

    assert filter_seqs.process_seq_by_class(class_3, 3) == expected


def test_class6_trimming():
    class_6 = Seq(
        (
            "GGGTTAGTTCAACGGAATCCCGGAAAGTAGCGAGTGTGAGACACGACGGTACCGCTCTATAAAATCATAAAGA"
            "GCGXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXX"
        )
    )
    expected = Seq(
        (
            "GGGTTAGTTCAACGGAATCCCGGAAAGTAGCGAGTGTGAGACACGACGGTACCGCTCTATAAAATCATAAAGA"
            "GCG"
        )
    )

    assert filter_seqs.process_seq_by_class(class_6, 6) == expected


def test_class7_trimming():
    class_7 = Seq(
        (
            "GTGCGTGCATGTGTGTGTGTGAGGGTACGTGAGGTATGTGTAACACAATATAGTATAAAATACTAATATTGTA"
            "CAAAATAAAGGATTAAAAATCAAAGCACAATTTATCATTTTATCAAATTGTATTGAGACTAATATACATGTAA"
            "AATATTTAAGTACAATATTGGTTATAAAACATGATATATTAATTAATTTGCTTTTATGTTTTAGGCATATTAT"
            "TTACTATTAATTAAAAGTATTAAGTTTGTTATAAATAATGATTAACGATACAGTAGCTTATTATAAATAAGAT"
            "GAAATAATTGAAATAATTTGTGTATCAAATAATTACTATATTATTAAAGTGTTGATATTATACTCGTTAAAAA"
            "AAAAAAAAATATCCAAAAAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTT"
        )
    )
    expected = Seq(
        (
            "GTGCGTGCATGTGTGTGTGTGAGGGTACGTGAGGTATGTGTAACACAATATAGTATAAAATACTAATATTGTA"
            "CAAAATAAAGGATTAAAAATCAAAGCACAATTTATCATTTTATCAAATTGTATTGAGACTAATATACATGTAA"
            "AATATTTAAGTACAATATTGGTTATAAAACATGATATATTAATTAATTTGCTTTTATGTTTTAGGCATATTAT"
            "TTACTATTAATTAAAAGTATTAAGTTTGTTATAAATAATGATTAACGATACAGTAGCTTATTATAAATAAGAT"
            "GAAATAATTGAAATAATTTGTGTATCAAATAATTACTATATTATTAAAGTGTTGATATTATACTCGTTAAAAA"
            "AAAAAAAAATATCCAAAAA"
        )
    )

    assert filter_seqs.process_seq_by_class(class_7, 7) == expected
