from Bio.Seq import Seq
from helpers import filter_seqs


seq_without_x = Seq(
    (
        "TTTTTATAAGAATTGCAGTGTGATACGAAATACTAGAACATCATTTTATAATCCGTGTAATAAAAATTATAATCTAG"
        "TATGTGTACTGCATTAGATCAATGGTTTTATATATATATCTATATAGTTTATCGTGCTTATTTAACGAACGCTTTGT"
        "AAAAAAGTGTTTTTTTTTTTTGTATAAGCATTCACATTATTAAAAACATTATTATCAATTAATTTGAAAATTTTATT"
        "TCTATATTATATTATCGCAGGTATCGAGTATAATTACGCGAACACGATGCGGCATCTTTTTCAATATTATAAAATAA"
        "TTATATATGTATAATAATTACCTATAATAGATTCAATAATAAATATTCATTTAAAATATCTCTTAAAAGAGTTTTTT"
        "CTTTACAGCGGTATATCTTTCCATATAGTTATCATAACCATCAAGATTAGCAAATTGTTTTATCTCAAATAAATTTC"
        "CTTCAACAGACAGGACTGAAATTTTAGAATTTTTCAAAATTTTACTAGGTATTGCATTCAGTTGTAAACAATTTTCT"
        "TCAAGTCTTAATGT"
    )
)

class_1 = Seq(
    (
        "ACTCTTTNCTCAGCTATGCXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXACTGGAATCGGAATGCGCCG"
        "CACCAGGAGAAAAACCACGGTTCCTTGGTGTTCGCGAGCAGCGAGTAACGCATATTTTAATCTTTTTGATGATCGGT"
        "TGTTCGGTCCTACTCACACCAATGTTGAGACACATACCTATGCCGGTATTATTCGGCGTTTTTCTTTATATGGGAGT"
        "CGCTTCGTTGAAAGGACTTCAATTTTTCGACAGAATTTTAATTATGTTGATGCCGGTTAAATACCAACCCGATTATA"
        "TGTTTCTTCGTCAGGTACCTCGGCCGCGACCACGCTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXA"
    )
)

class_3 = Seq(
    (
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXACCTCCTATATATATATGTATATATATATATA"
        "TATATCAATGTGTAATACCGCTAGTTTTCTCTCGATTCGTTCGAAAATTGTGGCTCTTTCGGGCGAAACCGGCTGGG"
        "TCTGTGTGTACTCTCATCCTGTTTCGTGAACCGAAAGCTCCCTTTCTCCGAAGAAGAAGAATACATTTTTTTTTCGT"
        "GCGCGTAACACGCAACGGGCATTAAGTTACAAACGAAACGAGCTTTACCGCGTTCCTTCCCTTTAAGGGAGTCGCGG"
        "ATGTTATACAAATGAAAAGAAAAAG"
    )
)

class_6 = Seq(
    (
        "GGGTTAGTTCAACGGAATCCCGGAAAGTAGCGAGTGTGAGACACGACGGTACCGCTCTATAAAATCATAAAGAGCGX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    )
)

class_7 = Seq(
    (
        "GTGCGTGCATGTGTGTGTGTGAGGGTACGTGAGGTATGTGTAACACAATATAGTATAAAATACTAATATTGTACAAA"
        "ATAAAGGATTAAAAATCAAAGCACAATTTATCATTTTATCAAATTGTATTGAGACTAATATACATGTAAAATATTTA"
        "AGTACAATATTGGTTATAAAACATGATATATTAATTAATTTGCTTTTATGTTTTAGGCATATTATTTACTATTAATT"
        "AAAAGTATTAAGTTTGTTATAAATAATGATTAACGATACAGTAGCTTATTATAAATAAGATGAAATAATTGAAATAA"
        "TTTGTGTATCAAATAATTACTATATTATTAAAGTGTTGATATTATACTCGTTAAAAAAAAAAAAAATATCCAAAAAX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
        "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTTT"
    )
)


def test_seq_not_changed():
    assert filter_seqs.process_seq_by_class(seq_without_x, None) == seq_without_x


def test_class1_trimming():
    expected = Seq(
        (
            "ACTGGAATCGGAATGCGCCGCACCAGGAGAAAAACCACGGTTCCTTGGTGTTCGCGAGCAGCGAGTAACGCAT"
            "ATTTTAATCTTTTTGATGATCGGTTGTTCGGTCCTACTCACACCAATGTTGAGACACATACCTATGCCGGTAT"
            "TATTCGGCGTTTTTCTTTATATGGGAGTCGCTTCGTTGAAAGGACTTCAATTTTTCGACAGAATTTTAATTAT"
            "GTTGATGCCGGTTAAATACCAACCCGATTATATGTTTCTTCGTCAGGTACCTCGGCCGCGACCACGCT"
        )
    )
    assert filter_seqs.process_seq_by_class(class_1, 1) == expected
